# Generated by Django 5.0.4 on 2024-04-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cancerPrediction", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cancerprescreendata",
            name="age",
            field=models.IntegerField(null=True),
        ),
    ]
